
add_newline = false
scan_timeout = 10

format = """\
  $time\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $custom\
  $jobs\
  $character\
  """

[line_break]
disabled = true

[character]
symbol = "▸"
success_symbol = "[▸](bold green)"
error_symbol = "[▸](bold red)"
vicmd_symbol = "[❮](bold green)"

[time]
disabled = false
time_format = "[%T]"
format = "[$time]($style) "
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"

[git_branch]
version = ""
symbol = " "

[git_status]
disabled = true

[git_state]
disabled = true

[java]
disabled = true



[python]
disabled = true

[hg_branch]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style)[$read_only]($read_only_style) "

[hostname]
disabled = true

[golang]
disabled = true

[username]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[package]
disabled = true
